name: Run Letterboxd Scraper

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Set Up Python
        uses: actions/setup-python@v4  
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python3 python/updateMovies.py

      - name: Upload Scraped Data
        uses: actions/upload-artifact@v4 
        with:
          name: letterboxd-results
          path: movies.html
