name: Update List of Movies
on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python3 python/updateMovies.py

      - name: Update csv with new data
        run: |
          git config --global user.name "Updated List of Movies"
          git config --global user.email "gagarwal003@gmail.com"
          
          git add public/movies.csv
          
          # Check if there are changes to commit
          git commit -m "Updated List of Movies" || echo "No changes to commit"
          
          git push