name: Sync Movie Data

on:
  workflow_dispatch: # Manual triggering only (automatic sync now handled by Cloudflare Worker)

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync movie data from Dropbox
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: node sync-data.js

      - name: Generate manifests
        run: node generate-manifests.js

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Use the GitHub Actions bot identity so commits are not attributed to a personal account
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movies/*.json dates.json
          git commit -m "🎬 Update movie data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: No changes detected
        if: steps.check_changes.outputs.changes == 'false'
        run: echo "No new movie data to sync"
